title: xTHY Tech Blog
safe: true
lsi:false
permalink: pretty
pygments: true

markdown: redcarpet
redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
	  
rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
    # - generate_toc