# Site settings
title: THTYLE
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty

# Build settings
kramdown:
  input: GFM
permalink: /:year/:month/:title/

# Third-party services
# just leave empty to disable it
google_analytics: 
